package app;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import Classes.SQLConecc;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manu_
 */
public class AdminOpts extends javax.swing.JFrame {

    /**
     * Creates new form AdminOpts
     */
    public AdminOpts() {
        initComponents();
        LlenarTabla();
    }
// Connection con;
    Connection con = new Classes.SQLConecc().establecconecction();
    Statement ps;
    ResultSet rs;

    public void LlenarTabla() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            ps = con.createStatement();
            rs = ps.executeQuery("SELECT * FROM productos;");

            while (rs.next()) {// Id`, `FullName`, `Address`, `BirthDate
                Object[] row = new Object[jTable1.getColumnCount()];

                row[0] = rs.getInt("id");
                row[1] = rs.getString("Prodnombre");
                row[2] = rs.getString("Precio");
                row[3] = rs.getString("Stock");
                row[4] = rs.getString("Descripcion");
                model.addRow(row);

            }
        } catch (SQLException ex) {
            //  Logger.getLogger(AdminOpts.class.getName()).log(Level.SEVERE, null, ex);}
            JOptionPane.showMessageDialog(null, "NO SE PUDO CONECTAR" + ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jlabioart = new javax.swing.JLabel();
        windowBorder1 = new app.WindowBorder();
        gradientP31 = new app.GradientP3();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnn_Cerrar_Ses = new javax.swing.JButton();
        Jlabioart1 = new javax.swing.JLabel();
        btn_graficas = new javax.swing.JButton();
        btn_empldo = new javax.swing.JButton();
        btn_ventas = new javax.swing.JButton();
        Btn_Actulzr = new javax.swing.JButton();
        Btn_Add = new javax.swing.JButton();
        Btnn_Borar = new javax.swing.JButton();

        Jlabioart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        windowBorder1.setBackground(new java.awt.Color(153, 255, 255));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio", "Stock", "Descripcion"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(102, 255, 102));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(35);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(35);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(35);
            jTable1.getColumnModel().getColumn(2).setMinWidth(75);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(75);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(75);
            jTable1.getColumnModel().getColumn(3).setMinWidth(75);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(75);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(75);
        }

        btnn_Cerrar_Ses.setBackground(new java.awt.Color(255, 153, 153));
        btnn_Cerrar_Ses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnn_Cerrar_Ses.setForeground(new java.awt.Color(255, 255, 255));
        btnn_Cerrar_Ses.setText("Cerrar Session");
        btnn_Cerrar_Ses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnn_Cerrar_Ses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn_Cerrar_SesActionPerformed(evt);
            }
        });

        Jlabioart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/bioart_icon.png"))); // NOI18N

        btn_graficas.setBackground(java.awt.SystemColor.activeCaption);
        btn_graficas.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btn_graficas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/graph.png"))); // NOI18N
        btn_graficas.setText("Graficas");
        btn_graficas.setToolTipText("");
        btn_graficas.setActionCommand("Admin \nOpciones");
        btn_graficas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_graficas.setContentAreaFilled(false);
        btn_graficas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graficasActionPerformed(evt);
            }
        });

        btn_empldo.setBackground(java.awt.SystemColor.activeCaption);
        btn_empldo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btn_empldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/emply.png"))); // NOI18N
        btn_empldo.setText("Empleados");
        btn_empldo.setToolTipText("");
        btn_empldo.setActionCommand("Admin \nOpciones");
        btn_empldo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_empldo.setContentAreaFilled(false);
        btn_empldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empldoActionPerformed(evt);
            }
        });

        btn_ventas.setBackground(java.awt.SystemColor.activeCaption);
        btn_ventas.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btn_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/money_icon.png"))); // NOI18N
        btn_ventas.setText("Ventas");
        btn_ventas.setToolTipText("");
        btn_ventas.setActionCommand("Admin \nOpciones");
        btn_ventas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ventas.setContentAreaFilled(false);
        btn_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ventasActionPerformed(evt);
            }
        });

        Btn_Actulzr.setBackground(gradientP31.getBackground());
        Btn_Actulzr.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        Btn_Actulzr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/update.png"))); // NOI18N
        Btn_Actulzr.setText("Actualizar");
        Btn_Actulzr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Actulzr.setBorderPainted(false);
        Btn_Actulzr.setRequestFocusEnabled(false);
        Btn_Actulzr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ActulzrActionPerformed(evt);
            }
        });

        Btn_Add.setBackground(gradientP31.getBackground());
        Btn_Add.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        Btn_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/batabase_add.png"))); // NOI18N
        Btn_Add.setText("Agregar");
        Btn_Add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Add.setBorderPainted(false);
        Btn_Add.setRequestFocusEnabled(false);
        Btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AddActionPerformed(evt);
            }
        });

        Btnn_Borar.setBackground(gradientP31.getBackground());
        Btnn_Borar.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        Btnn_Borar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/delete.png"))); // NOI18N
        Btnn_Borar.setText("Borrar");
        Btnn_Borar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btnn_Borar.setBorderPainted(false);
        Btnn_Borar.setRequestFocusEnabled(false);
        Btnn_Borar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnn_BorarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gradientP31Layout = new javax.swing.GroupLayout(gradientP31);
        gradientP31.setLayout(gradientP31Layout);
        gradientP31Layout.setHorizontalGroup(
            gradientP31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientP31Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientP31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jlabioart1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gradientP31Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnn_Cerrar_Ses, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gradientP31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_graficas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ventas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_empldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(gradientP31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradientP31Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(gradientP31Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Actulzr, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(Btnn_Borar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        gradientP31Layout.setVerticalGroup(
            gradientP31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(gradientP31Layout.createSequentialGroup()
                .addGroup(gradientP31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(gradientP31Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jlabioart1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(btn_empldo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btn_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btn_graficas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnn_Cerrar_Ses, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gradientP31Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, gradientP31Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(gradientP31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Actulzr, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btnn_Borar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout windowBorder1Layout = new javax.swing.GroupLayout(windowBorder1);
        windowBorder1.setLayout(windowBorder1Layout);
        windowBorder1Layout.setHorizontalGroup(
            windowBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowBorder1Layout.createSequentialGroup()
                .addComponent(gradientP31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        windowBorder1Layout.setVerticalGroup(
            windowBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientP31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnn_Cerrar_SesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn_Cerrar_SesActionPerformed
        // TODO add your handling code here:
        new Cerrar_Secion().setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btnn_Cerrar_SesActionPerformed

    private void btn_empldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empldoActionPerformed
        // TODO add your handling code here:
        new Empleado_Findr().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_empldoActionPerformed

    private void btn_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ventasActionPerformed

    private void btn_graficasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graficasActionPerformed
        // TODO add your handling code here:
        new Graficas_Opts().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_graficasActionPerformed

    private void Btn_ActulzrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ActulzrActionPerformed
        // TODO add your handling code here:
        Connection con = new Classes.SQLConecc().establecconecction();
        Statement st;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            st = con.createStatement();
            for (int i = 0; i < model.getRowCount(); i++) {
                int id = Integer.valueOf(model.getValueAt(i, 0).toString());
                String Prodnom = model.getValueAt(i, 1).toString();
                Double price = Double.valueOf(model.getValueAt(i, 2).toString());
                int stock = Integer.valueOf(model.getValueAt(i, 3).toString());
                String ProDescp = model.getValueAt(i, 4).toString();
                // String actualizarquery ="UPDATE negocio_bd.productos SET Prodnombre ="+Prodnom+", Precio = "+price+", Stock = "+stock+", Descripcion = "+ProDescp+" WHERE id="+id;
                // String actualizarquery ="UPDATE `productos` SET `Prodnombre`='"+Prodnom+ /*"',`Address`='"+adr+"',`BirthDate`='\"+bdate+\*/"' WHERE `Id` = " +id;
                String actualizarquery = "UPDATE `productos` SET `Prodnombre`='" + Prodnom + "',`Precio`='" + price + "',`Stock`='" + stock + "',`Descripcion`='" + ProDescp + "' WHERE `Id` = " + id;
                st.addBatch(actualizarquery);

            }
            int[] actulzrfila = st.executeBatch();
            System.out.println(actulzrfila.length);
            JOptionPane.showMessageDialog(null, "Se ACTUALIZO correctamente la base de datos");
        } catch (SQLException ex) {
            Logger.getLogger(AdminOpts.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_Btn_ActulzrActionPerformed

    private void Btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AddActionPerformed
        // TODO add your handling code here:
        Connection con = new Classes.SQLConecc().establecconecction();
        Statement st;
        String nom = JOptionPane.showInputDialog("Ingrese el nombre");
        Double precio = Double.valueOf(JOptionPane.showInputDialog("Ingrese el precio "));
        int stock = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el stock "));
        String descripcion = JOptionPane.showInputDialog("Ingrese la descripcion ");
        Object rowData[] = new Object[5];
        rowData[1] = nom;
        rowData[2] = precio;
        rowData[3] = stock;
        rowData[4] = descripcion;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        try {
            st = con.createStatement();
            String agregarquery = "INSERT INTO `negocio_bd`.`productos` (`Prodnombre`, `Precio`, `Stock`, `Descripcion`) VALUES ('"+nom+"', '"+precio+"', '"+stock+"', '"+descripcion+"')";
                st.addBatch(agregarquery);
                int[] agrgrfila = st.executeBatch();
                System.out.println(agrgrfila.length);
                model.addRow(rowData);
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(AdminOpts.class.getName()).log(Level.SEVERE, null, ex);
        }
        new AdminOpts().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_Btn_AddActionPerformed

    private void Btnn_BorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnn_BorarActionPerformed
        // TODO add your handling code here:
        Connection con = new Classes.SQLConecc().establecconecction();
        Statement st;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            st = con.createStatement();
            for (int i = 0; i < model.getRowCount(); i++) {
                int id = Integer.valueOf(model.getValueAt(i, 0).toString());
                // String actualizarquery ="UPDATE negocio_bd.productos SET Prodnombre ="+Prodnom+", Precio = "+price+", Stock = "+stock+", Descripcion = "+ProDescp+" WHERE id="+id;
                // String actualizarquery ="UPDATE `productos` SET `Prodnombre`='"+Prodnom+ /*"',`Address`='"+adr+"',`BirthDate`='\"+bdate+\*/"' WHERE `Id` = " +id;
                String actualizarquery = "UPDATE `productos` SET `id`='" + id;
                st.addBatch(actualizarquery);

            }
            int[] actulzrfila = st.executeBatch();
            System.out.println(actulzrfila.length);
            JOptionPane.showMessageDialog(null, "Se ACTUALIZO el ID correctamente");
        } catch (SQLException ex) {
            Logger.getLogger(AdminOpts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btnn_BorarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOpts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOpts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOpts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOpts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOpts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Actulzr;
    private javax.swing.JButton Btn_Add;
    private javax.swing.JButton Btnn_Borar;
    private javax.swing.JLabel Jlabioart;
    private javax.swing.JLabel Jlabioart1;
    private javax.swing.JButton btn_empldo;
    private javax.swing.JButton btn_graficas;
    private javax.swing.JButton btn_ventas;
    private javax.swing.JButton btnn_Cerrar_Ses;
    private app.GradientP3 gradientP31;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private app.WindowBorder windowBorder1;
    // End of variables declaration//GEN-END:variables
}
