
package app;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JTextField;
import Classes.Login;
import javax.swing.ImageIcon;
import app.Generacion_De_Tickets;
import java.awt.event.KeyEvent;
/**
 *
 * @author Alex
 */
public class Employ_Login extends javax.swing.JFrame {
 ImageIcon imagenlogo = new ImageIcon("logobio.jpg");

    /**
     * Creates new form ConfirSalir
     */
   

    public Employ_Login() {
        initComponents();
        Jlabioart.setIcon(imagenlogo);
        setBackground(new Color(0,0,0,0));
        addPlaceholderStyle(txtemploy);
        addPlaceholderStyle(txtcontra);
        Classes.SQLConecc objtConct = new Classes.SQLConecc();
        objtConct.establecconecction();
     
        
    }
    //agregar estiilode texto demo
  
    
    //Metodos para el texto demo
    public void addPlaceholderStyle(JTextField textfield){
    Font font =textfield.getFont();
    font = font.deriveFont(Font.ITALIC);
    textfield.setFont(font);
    textfield.setForeground(Color.gray);//este es el color de el texto
    }
    public void removePlaceholderStyle(JTextField textfield){
       Font font =textfield.getFont();
    font = font.deriveFont(Font.PLAIN|Font.BOLD);
    textfield.setFont(font);
    textfield.setForeground(Color.black);//este es el color de el texto
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new app.WindowBorder();
        gradientP2 = new app.GradientP();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtemploy = new javax.swing.JTextField();
        txtcontra = new javax.swing.JPasswordField();
        Ingresarbtnn = new javax.swing.JButton();
        Jlabioart = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN LOGIN");
        setBounds(new java.awt.Rectangle(570, 330, 0, 0));
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        panelGradient1.setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText(" SISTEMA LOGIN");

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel2.setText(" ID");

        jLabel3.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel3.setText("Contraseña");

        txtemploy.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtemployFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemployFocusLost(evt);
            }
        });
        txtemploy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemployActionPerformed(evt);
            }
        });
        txtemploy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemployKeyPressed(evt);
            }
        });

        txtcontra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcontra.setText("Contraseña");
        txtcontra.setEchoChar('\u0000');
        txtcontra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcontraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcontraFocusLost(evt);
            }
        });
        txtcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontraActionPerformed(evt);
            }
        });
        txtcontra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcontraKeyPressed(evt);
            }
        });

        Ingresarbtnn.setBackground(new java.awt.Color(0, 51, 255));
        Ingresarbtnn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ingresarbtnn.setForeground(new java.awt.Color(255, 255, 255));
        Ingresarbtnn.setText("Ingresar->");
        Ingresarbtnn.setActionCommand("Admin \nOpciones");
        Ingresarbtnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarbtnnActionPerformed(evt);
            }
        });

        Jlabioart.setForeground(new java.awt.Color(255, 255, 255));

        jButton4.setBackground(new java.awt.Color(255, 153, 153));
        jButton4.setText("Cerrar Sistema");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 255, 153));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Admin Login");
        jButton5.setActionCommand("Admin \nOpciones");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gradientP2Layout = new javax.swing.GroupLayout(gradientP2);
        gradientP2.setLayout(gradientP2Layout);
        gradientP2Layout.setHorizontalGroup(
            gradientP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientP2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(gradientP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(gradientP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(gradientP2Layout.createSequentialGroup()
                            .addGap(172, 172, 172)
                            .addGroup(gradientP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(gradientP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtemploy)
                                .addComponent(txtcontra, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                        .addGroup(gradientP2Layout.createSequentialGroup()
                            .addComponent(jButton4)
                            .addGap(226, 226, 226)
                            .addComponent(Ingresarbtnn))
                        .addGroup(gradientP2Layout.createSequentialGroup()
                            .addGap(244, 244, 244)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(gradientP2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jlabioart, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(250, 250, 250))
        );
        gradientP2Layout.setVerticalGroup(
            gradientP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientP2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(gradientP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradientP2Layout.createSequentialGroup()
                        .addComponent(Jlabioart, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gradientP2Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gradientP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientP2Layout.createSequentialGroup()
                        .addGroup(gradientP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(gradientP2Layout.createSequentialGroup()
                                .addComponent(txtemploy, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                .addGap(1, 1, 1)))
                        .addGap(26, 26, 26)
                        .addGroup(gradientP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Ingresarbtnn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientP2Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addComponent(gradientP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarbtnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarbtnnActionPerformed
        
        Classes.Login objLogin= new Classes.Login();
        objLogin.validademploy(txtemploy, txtcontra);
 
        if(Classes.Login.ismngr==true){
        //g.setVisible(true);
        this.dispose();
        }
        
    }//GEN-LAST:event_IngresarbtnnActionPerformed

    private void txtemployFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemployFocusGained
        // TODO add your handling code here:
        if(txtemploy.getText().equals("ID")){
            txtemploy.setText(null);
            txtemploy.requestFocus();
            //quitar estilo de demo
            removePlaceholderStyle(txtemploy);
        
        }
    }//GEN-LAST:event_txtemployFocusGained

    private void txtcontraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontraFocusGained
        // TODO add your handling code here:
        if(txtcontra.getText().equals("Contraseña")){
            txtcontra.setText(null);
            txtcontra.requestFocus();
            //Poner forma de contraseña
            txtcontra.setEchoChar('\u2022');
            //quitar estilo de demo
            removePlaceholderStyle(txtcontra);
        
        }
    }//GEN-LAST:event_txtcontraFocusGained

    private void txtemployFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemployFocusLost
        // TODO add your handling code here:
        if(txtemploy.getText().length()==0){
        addPlaceholderStyle(txtemploy);
        txtemploy.setText("ID");
        
        }
    }//GEN-LAST:event_txtemployFocusLost

    private void txtcontraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontraFocusLost
        // TODO add your handling code here:
        if(txtcontra.getText().length()==0){
        addPlaceholderStyle(txtcontra);
        txtcontra.setText("Contraseña");
        txtcontra.setEchoChar('\u0000');
        
        }
    }//GEN-LAST:event_txtcontraFocusLost

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowLostFocus

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new ConfirSalir().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtemployActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemployActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemployActionPerformed

    private void txtcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontraActionPerformed

    private void txtcontraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontraKeyPressed
        // TODO add your handling code here:
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        Classes.Login objLogin= new Classes.Login();
        objLogin.validademploy(txtemploy, txtcontra);
 
        if(Classes.Login.ismngr==true){
        //g.setVisible(true);
        this.dispose();
        }
            }
    }//GEN-LAST:event_txtcontraKeyPressed

    private void txtemployKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemployKeyPressed
        // TODO add your handling code here:
       
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {txtcontra.requestFocus();}
    }//GEN-LAST:event_txtemployKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new Admin_Login2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employ_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employ_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employ_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employ_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employ_Login().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Ingresarbtnn;
    private javax.swing.JLabel Jlabioart;
    private app.GradientP gradientP2;
    private javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private app.WindowBorder panelGradient1;
    private javax.swing.JPasswordField txtcontra;
    public javax.swing.JTextField txtemploy;
    // End of variables declaration//GEN-END:variables
}
