package app;

import java.awt.Color;
//import java.awt.Font;
//import javax.swing.JTextField;
//import Classes.Login;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alex
 */
public class Empleado_Findr extends javax.swing.JFrame {

    /**
     * Creates new form ConfirSalir
     */
    public Empleado_Findr() {
        initComponents();
        LlenarTabla();
        setBackground(new Color(0, 0, 0, 0));

        Classes.SQLConecc objtConct = new Classes.SQLConecc();
        objtConct.establecconecction();

    }
       Connection con = new  Classes.SQLConecc().establecconecction();
    Statement ps;
    ResultSet rs;
    
    public void LlenarTabla(){
 DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            ps = con.createStatement();
            rs = ps.executeQuery("SELECT * FROM empleado;");
            
            while(rs.next()){// Id`, `FullName`, `Address`, `BirthDate
                Object[] row = new Object[jTable1.getColumnCount()];
                row[0] = rs.getString("idEmpleado"); 
               row[1] = rs.getString("EmpleadoUsrname"); 
                row[2] = rs.getString("EmpleadoPsswrd");
                row[3] = rs.getString("EmpleadoNombr");
             //   row[3] = rs.getString("Descripcion");
                 model.addRow(row);
                
               
                
            }}catch(SQLException ex){
      //  Logger.getLogger(AdminOpts.class.getName()).log(Level.SEVERE, null, ex);}
       JOptionPane.showMessageDialog(null, "NO SE PUDO CONECTAR"+ ex.toString());
       }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new app.WindowBorder();
        gradientP2 = new app.GradientP();
        jLabel1 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_ventas = new javax.swing.JButton();
        btn_graficas = new javax.swing.JButton();
        btnn_Cerrar_Ses = new javax.swing.JButton();
        Btn_Actulzr = new javax.swing.JButton();
        Btn_Add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN LOGIN");
        setBounds(new java.awt.Rectangle(570, 330, 0, 0));
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        panelGradient1.setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText("EMPLEADOS ");

        BackButton.setBackground(java.awt.SystemColor.activeCaption);
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/iconarrow.png"))); // NOI18N
        BackButton.setText(" Regresar");
        BackButton.setActionCommand("Admin \nOpciones");
        BackButton.setContentAreaFilled(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre De Usuario", "Contraseña", "Nombre Completo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(75);
        }

        btn_ventas.setBackground(java.awt.SystemColor.activeCaption);
        btn_ventas.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btn_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/money_icon.png"))); // NOI18N
        btn_ventas.setText("Ventas");
        btn_ventas.setToolTipText("");
        btn_ventas.setActionCommand("Admin \nOpciones");
        btn_ventas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ventas.setContentAreaFilled(false);
        btn_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ventasActionPerformed(evt);
            }
        });

        btn_graficas.setBackground(java.awt.SystemColor.activeCaption);
        btn_graficas.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btn_graficas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/graph.png"))); // NOI18N
        btn_graficas.setText("Graficas");
        btn_graficas.setToolTipText("");
        btn_graficas.setActionCommand("Admin \nOpciones");
        btn_graficas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_graficas.setContentAreaFilled(false);
        btn_graficas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graficasActionPerformed(evt);
            }
        });

        btnn_Cerrar_Ses.setBackground(new java.awt.Color(255, 153, 153));
        btnn_Cerrar_Ses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnn_Cerrar_Ses.setForeground(new java.awt.Color(255, 255, 255));
        btnn_Cerrar_Ses.setText("Cerrar Session");
        btnn_Cerrar_Ses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnn_Cerrar_Ses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn_Cerrar_SesActionPerformed(evt);
            }
        });

        Btn_Actulzr.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        Btn_Actulzr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/update.png"))); // NOI18N
        Btn_Actulzr.setText("Actualizar");
        Btn_Actulzr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Actulzr.setBorderPainted(false);
        Btn_Actulzr.setRequestFocusEnabled(false);
        Btn_Actulzr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ActulzrActionPerformed(evt);
            }
        });

        Btn_Add.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        Btn_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/batabase_add.png"))); // NOI18N
        Btn_Add.setText("Agregar");
        Btn_Add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Add.setBorderPainted(false);
        Btn_Add.setRequestFocusEnabled(false);
        Btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gradientP2Layout = new javax.swing.GroupLayout(gradientP2);
        gradientP2.setLayout(gradientP2Layout);
        gradientP2Layout.setHorizontalGroup(
            gradientP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(113, 113, 113)
                .addComponent(Btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(Btn_Actulzr, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(gradientP2Layout.createSequentialGroup()
                .addGroup(gradientP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gradientP2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(gradientP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnn_Cerrar_Ses, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(gradientP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_graficas, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(btn_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        gradientP2Layout.setVerticalGroup(
            gradientP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientP2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Actulzr, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(gradientP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradientP2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btn_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btn_graficas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnn_Cerrar_Ses, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(gradientP2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:

        new AdminOpts().setVisible(true);
        this.dispose();


    }//GEN-LAST:event_BackButtonActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowLostFocus

    private void btn_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ventasActionPerformed

    private void btn_graficasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graficasActionPerformed
        // TODO add your handling code here:
        new Graficas_Opts().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_graficasActionPerformed

    private void btnn_Cerrar_SesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn_Cerrar_SesActionPerformed
        // TODO add your handling code here:
        new Cerrar_Secion().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnn_Cerrar_SesActionPerformed

    private void Btn_ActulzrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ActulzrActionPerformed
        // TODO add your handling code here:
        Connection con = new Classes.SQLConecc().establecconecction();
        Statement st;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            st = con.createStatement();
            for (int i = 0; i < model.getRowCount(); i++) {
                int id = Integer.valueOf(model.getValueAt(i, 0).toString());
                String EmpleadoUsrname = model.getValueAt(i, 1).toString();
                String EmpleadoPsswrd = model.getValueAt(i, 2).toString();
                String EmpleadoNm = model.getValueAt(i, 3).toString();
                // String actualizarquery ="UPDATE negocio_bd.productos SET Prodnombre ="+Prodnom+", Precio = "+price+", Stock = "+stock+", Descripcion = "+ProDescp+" WHERE id="+id;
                // String actualizarquery ="UPDATE `productos` SET `Prodnombre`='"+Prodnom+ /*"',`Address`='"+adr+"',`BirthDate`='\"+bdate+\*/"' WHERE `Id` = " +id;
                String actualizarquery = "UPDATE `empleado` SET `EmpleadoUsrname`='" + EmpleadoUsrname + "',`EmpleadoPsswrd`='" + EmpleadoPsswrd + "',`EmpleadoNombr`='" + EmpleadoNm + "' WHERE `idEmpleado` = " + id;
                st.addBatch(actualizarquery);

            }
            int[] actulzrfila = st.executeBatch();
            System.out.println(actulzrfila.length);
            JOptionPane.showMessageDialog(null, "Se ACTUALIZO correctamente la base de datos de Empleados");
        } catch (SQLException ex) {
            Logger.getLogger(AdminOpts.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Btn_ActulzrActionPerformed

    private void Btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AddActionPerformed
        // TODO add your handling code here:
        Connection con = new Classes.SQLConecc().establecconecction();
        Statement st;
        String usrnm = JOptionPane.showInputDialog("Ingrese el Nuevo Usuario");
        String contra = JOptionPane.showInputDialog("Ingrese la contraseña ");
         String nomcomp = JOptionPane.showInputDialog("Ingrese el Nombre Completo");
        //String descripcion = JOptionPane.showInputDialog("Ingrese la descripcion ");
        Object rowData[] = new Object[5];
        rowData[1] = usrnm;
        rowData[2] = contra;
        rowData[3] = nomcomp;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        try {
            st = con.createStatement();
            String agregarquery = "INSERT INTO `negocio_bd`.`empleado` (`EmpleadoUsrname`, `EmpleadoPsswrd`, `EmpleadoNombr`) VALUES ('"+usrnm+"', '"+contra+"', '"+nomcomp+"')";
            st.addBatch(agregarquery);
            int[] agrgrfila = st.executeBatch();
            System.out.println(agrgrfila.length);
            model.addRow(rowData);
        }

        catch (SQLException ex) {
            Logger.getLogger(AdminOpts.class.getName()).log(Level.SEVERE, null, ex);
        }
        new Empleado_Findr().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleado_Findr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleado_Findr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleado_Findr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleado_Findr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleado_Findr().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton Btn_Actulzr;
    private javax.swing.JButton Btn_Add;
    private javax.swing.JButton btn_graficas;
    private javax.swing.JButton btn_ventas;
    private javax.swing.JButton btnn_Cerrar_Ses;
    private app.GradientP gradientP2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private app.WindowBorder panelGradient1;
    // End of variables declaration//GEN-END:variables
}
