
package app;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import Classes.SQLConecc;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manu_
 */
public class Graficas_Opts extends javax.swing.JFrame {

    /**
     * Creates new form AdminOpts
     */
    public Graficas_Opts() {
        initComponents();
      
    }
// Connection con;
     Connection con = new  Classes.SQLConecc().establecconecction();
    Statement ps;
    ResultSet rs;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jlabioart = new javax.swing.JLabel();
        windowBorder1 = new app.WindowBorder();
        gradientP31 = new app.GradientP3();
        btnn_Cerrar_Ses = new javax.swing.JButton();
        Jlabioart1 = new javax.swing.JLabel();
        btn_empldo = new javax.swing.JButton();
        btn_ventas = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        Jlabioart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        windowBorder1.setBackground(new java.awt.Color(153, 255, 255));

        btnn_Cerrar_Ses.setBackground(new java.awt.Color(255, 153, 153));
        btnn_Cerrar_Ses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnn_Cerrar_Ses.setForeground(new java.awt.Color(255, 255, 255));
        btnn_Cerrar_Ses.setText("Cerrar Session");
        btnn_Cerrar_Ses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnn_Cerrar_Ses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn_Cerrar_SesActionPerformed(evt);
            }
        });

        Jlabioart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/bioart_icon.png"))); // NOI18N

        btn_empldo.setBackground(java.awt.SystemColor.activeCaption);
        btn_empldo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btn_empldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/emply.png"))); // NOI18N
        btn_empldo.setText("Empleados");
        btn_empldo.setToolTipText("");
        btn_empldo.setActionCommand("Admin \nOpciones");
        btn_empldo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_empldo.setContentAreaFilled(false);
        btn_empldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empldoActionPerformed(evt);
            }
        });

        btn_ventas.setBackground(java.awt.SystemColor.activeCaption);
        btn_ventas.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btn_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/money_icon.png"))); // NOI18N
        btn_ventas.setText("Ventas");
        btn_ventas.setToolTipText("");
        btn_ventas.setActionCommand("Admin \nOpciones");
        btn_ventas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ventas.setContentAreaFilled(false);
        btn_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ventasActionPerformed(evt);
            }
        });

        BackButton.setBackground(java.awt.SystemColor.activeCaption);
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/iconarrow.png"))); // NOI18N
        BackButton.setText(" Regresar");
        BackButton.setActionCommand("Admin \nOpciones");
        BackButton.setContentAreaFilled(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gradientP31Layout = new javax.swing.GroupLayout(gradientP31);
        gradientP31.setLayout(gradientP31Layout);
        gradientP31Layout.setHorizontalGroup(
            gradientP31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientP31Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientP31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradientP31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Jlabioart1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(gradientP31Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(btnn_Cerrar_Ses, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(gradientP31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_ventas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_empldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(905, Short.MAX_VALUE))
        );
        gradientP31Layout.setVerticalGroup(
            gradientP31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(gradientP31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jlabioart1)
                .addGap(57, 57, 57)
                .addComponent(btn_empldo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btn_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnn_Cerrar_Ses, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout windowBorder1Layout = new javax.swing.GroupLayout(windowBorder1);
        windowBorder1.setLayout(windowBorder1Layout);
        windowBorder1Layout.setHorizontalGroup(
            windowBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientP31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        windowBorder1Layout.setVerticalGroup(
            windowBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientP31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnn_Cerrar_SesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn_Cerrar_SesActionPerformed
        // TODO add your handling code here:
          new Cerrar_Secion().setVisible(true);
        this.dispose();
        
     
    }//GEN-LAST:event_btnn_Cerrar_SesActionPerformed

    private void btn_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ventasActionPerformed

    private void btn_empldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empldoActionPerformed
        // TODO add your handling code here:
        new Empleado_Findr().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_empldoActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
 new AdminOpts().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graficas_Opts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graficas_Opts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graficas_Opts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graficas_Opts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graficas_Opts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Jlabioart;
    private javax.swing.JLabel Jlabioart1;
    private javax.swing.JButton btn_empldo;
    private javax.swing.JButton btn_ventas;
    private javax.swing.JButton btnn_Cerrar_Ses;
    private app.GradientP3 gradientP31;
    private app.WindowBorder windowBorder1;
    // End of variables declaration//GEN-END:variables
}
